name: core
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.8
  dio: 5.9.2
  path_provider: 2.1.5
  path: 1.9.1
  equatable: 2.0.8
  objectbox: 5.2.0
  objectbox_flutter_libs: 5.2.0
  gap: 3.0.1
  in_app_review: 2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint_rules:
    path: ../lint_rules
  build_runner: 2.13.1
  objectbox_generator: 5.2.0


flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
